config/routes.rb
Rails.application.routes.draw do

  root 'measurements#index'

  resources :measurements do
    resources :records, only: :create
  end
  resources :infos, only: :index
  resources :managements#, only: :edit

  get 'export_csv', to: 'measurements#export_csv', path: "/measurements/:id/export_csv"

  get 'auto_reload', to: 'measurements#auto_reload', path: "/measurements/:id/auto_reload"

  get 'reset_db', to: 'managements#reset_db', path: "/managements/:id/reset_db"

end

app/models/management.rb
class Management < ActiveRecord::Base
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base

  has_many :records, :dependent => :delete_all

end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :measurement
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController

  def cpu_temperature
    cpu_temp = (`vcgencmd measure_temp` || 'not supported').strip  # XXX - vcgencmd requires the user to be in 'video' group
    if cpu_temp =~ /temp=(.*)/
    	cpu_temp = $1
    end
    cpu_temp
  end

  def memory_splits
    mem_splits = `vcgencmd get_mem arm && vcgencmd get_mem gpu`  # XXX - vcgencmd requires the user to be in 'video' group
  end

  def index
  	@uname = `uname -a`
  	@uptime = `uptime`
  	@df = `df -h`
  	@mem_splits = memory_splits
  	@free = `free -o -h`
  	@cpu_temp = cpu_temperature
    @cpu_info = `cat /proc/cpuinfo`
  end

end

app/controllers/managements_controller.rb
# -*- coding: utf-8 -*-
class ManagementsController < ApplicationController
  
  def edit
    @management = Management.find(1)
  end
  
  
  def update
    @management = Management.find(1)
    if @management.update(params[:management].permit(:kei))
      redirect_to measurements_path, notice: '更新されました！'
    else
      render action: 'edit'
    end
  end

  def reset_db
    `rake -f /home/pi/gomihiroi/grass/Rakefile db:migrate:reset && rake -f /home/pi/gomihiroi/grass/Rakefile db:seed`
    redirect_to measurements_path, notice: 'データベースが正常にリセットされました！'
  end
  
end

app/controllers/measurements_controller.rb
# coding: utf-8
class MeasurementsController < ApplicationController

  def index
    @measurements = Measurement.all
    @management = Management.find(1)
  end


  def show
    @measurement = Measurement.find(params[:id])
    @records = @measurement.records

    if @records.any?
      File.open("public/out.dat", "w") do |io|
        @records.each do |r|
          io.print "#{r.x} #{r.y} -#{r.depth}\n" 
        end
      end
      # gnuplotでグラフ作成実行
      `gplot.sh #{params[:id]}`
    end
  end


  def export_csv
    @measurement = Measurement.find(params[:id])
    @records = @measurement.records
    data = CSV.generate do |csv|
      csv << ["id", "depth", "x", "y", "latitude", "longitude"]
      @records.each do |r|
#        csv << [r.id, r.depth, r.x, r.y, r.latitude, r.longitude]
        csv << [r.latitude, r.longitude]
      end
    end
    send_data(data, type: 'text/csv', filename: "Record_#{@measurement.id}_#{Time.now.strftime('%Y%m%d%H%M%S')}")
  end


  def auto_reload
    @measurements = Measurement.find(params[:id]).records.order("id DESC").limit(50)
    r_id = []
    depth = []
    @measurements.each do |m|
      r_id.push(m.id)
      depth.push(-1*m.depth)
    end


    @graph = LazyHighCharts::HighChart.new('graph') do |f|
      f.chart(:type => "area")
#      f.title(text: 'ItemXXXの在庫の推移')
      f.xAxis(categories: r_id)
      f.series(name: 'depth', data: depth)
    end
  end


  def new
    @measurement = Measurement.new
  end


  def create
    @measurement = Measurement.new(params[:measurement].permit(:comment))
    @management = Management.find(1)
    if @management.state == true
      redirect_to measurements_path, notice: '現在その操作はできません！'
    elsif @measurement.save
      @management.state = true
      @management.measurementid = @management.measurementid + 1
      @management.save
      redirect_to measurements_path, notice: '計測を開始しました！'
    else
      render action 'new'
    end
  end


  def edit
    @measurement = Measurement.find(params[:id])
  end


  def update
    @measurement = Measurement.find(params[:id])
    if @measurement.update(params[:measurement].permit(:comment))
      redirect_to measurements_path, notice: '更新されました！'
    else
      render action: 'edit'
    end
  end


  def destroy
    @measurement = Measurement.find(params[:id])
    @measurement.destroy
    redirect_to measurements_path
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  def create
    @measurement = Measurement.find(params[:measurement_id])
    @record = Measurement.find(params[:measurement_id]).records.create(params[:record].permit(:depth, :latitude, :longitude))
    redirect_to measurement_path(@measurement)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/infos/index.html.erb
<h1>Information of System</h1>

<h2>Raspberry Pi</h2>
<table class="table table-striped table-bordered">
	<thead>
		<tr><th>Item</th><th>Value</th></tr>
	</thead>
	<tbody>
		<tr><td>uname</td><td><%= @uname %></td></tr>
		<tr><td>uptime</td><td><%= @uptime %></td></tr>
		<tr><td>df</td><td><%= @df %></td></tr>
		<tr><td>mem_splits</td><td><%= @mem_splits %></td></tr>
		<tr><td>free</td><td><%= @free %></td></tr>
		<tr><td>cpu_temp</td><td><%= @cpu_temp %></td></tr>
		<tr><td>cpu_info</td><td><%= @cpu_info %></td></tr>
	</tbody>
</table>


<h2>GRasS</h2>
<h3>ver.0.2.0</h3>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--[if IE]><script type="text/javascript" src="javascript/excanvas.js"></script><![endif]-->
  <title>GRasS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %> 
  <meta content="width=device-width, initial-scale=1" name="viewport">
</head>

<body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
	<%= link_to raw("GRasS<sup>devel</sup>"), root_path, :class => "navbar-brand" %>

      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if current_page?(measurements_path) %> <%= 'active' if current_page?(root_path) %>"><%= link_to "Data" , measurements_path %></li>
          <li class="<%= 'active' if current_page?(edit_management_path(1)) %>"><%= link_to "Settings" , edit_management_path(1) %></li> 
          <li class="<%= 'active' if current_page?(infos_path) %>"><%= link_to "Info" , infos_path %></li>          
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

  <div class="container" style="margin: 70px 0 0 0">
    <%= render 'layouts/messages' %>

    <%= yield %>　　<!-- ※この行は各ページを表示するための、最初から存在する。 -->
  </div><!-- /.container -->
</body>
</html>

app/views/managements/edit.html.erb
<h1>Settings</h1>

<hr>
<h2>系番号設定</h2>
<p>平面直角座標の系番号を選択してください。</p>

<%= simple_form_for(@management) do |f| %>
	<%= f.select :kei, [["1: 東経129度30分0秒，北緯33度0分0秒", "1"],["2: 東経131度0分0秒，北緯33度0分0秒", "2"], ["3: 東経132度10分0秒，北緯36度0分0秒", "3"], ["4: 東経133度30分0秒，北緯33度0分0秒", "4"], ["5: 東経134度20分0秒，北緯36度0分0秒", "5"], ["6: 東経136度0分0秒，北緯36度0分0秒", "6"], ["7: 東経137度10分0秒，北緯36度0分0秒", "7"], ["8: 東経138度30分0秒，北緯36度0分0秒", "8"], ["9: 東経139度50分0秒，北緯36度0分0秒", "9"], ["10: 東経140度50分0秒，北緯40度0分0秒", "10"], ["11: 東経140度15分0秒，北緯44度0分0秒", "11"], ["12: 東経142度15分0秒，北緯44度0分0秒", "12"], ["13: 東経144度15分0秒，北緯44度0分0秒", "13"], ["14: 東経142度0分0秒，北緯26度0分0秒", "14"], ["15: 東経127度30分0秒，北緯26度0分0秒", "15"], ["16: 東経124度0分0秒，北緯26度0分0秒", "16"], ["17: 東経131度0分0秒，北緯26度0分0秒", "17"], ["18: 東経136度0分0秒，北緯20度0分0秒", "18"], 
	["19: 東経154度0分0秒，北緯26度0分0秒", "19"]], {}, {class: "form-control"} %>
  </br>
  <span class="glyphicon glyphicon-exclamation-sign"></span> 次回の測定から設定が有効になります
  <div class="form-actions">
    <%= f.button :submit, "Update Settings", :class => 'btn-primary' %>
  </div>
<% end %>

<br>
<hr>
<h2>データベース初期化</h2>
<span class="glyphicon glyphicon-exclamation-sign"></span> データベースを初期化します。
<br>
<%= link_to "Reset Database", reset_db_path, :class => "btn btn-danger", :data => {:confirm =>"データベースを初期化します。よろしいですか？
注：この処理には時間がかかります。処理中にブラウザを閉じたり、他の操作をしないでください。アプリケーションが破損する恐れがあります。"} %>

app/views/measurements/auto_reload.html.erb
<h1>Auto Reload Graph</h1>

<SCRIPT Language="JavaScript">
function Rld()
{
location.reload();
}
setTimeout("Rld()",10000);
</SCRIPT>


<%= high_chart("sample", @graph) %>

app/views/measurements/edit.html.erb
<h2>何かコメントがあれば入力してください(任意)</h2>

<%= simple_form_for(@measurement) do |f| %>
  <%= f.input :comment %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
  </div>
<% end %>

app/views/measurements/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="span12 pull-center">
      <% if @management.state == true %>
      <div class="alert alert-danger">
      <h2><span class="label label-danger">Status</span> 計測中</h2>
      <p><span class="glyphicon glyphicon-exclamation-sign"></span> 計測中は他のデータを操作することができません。</p>
      <% else %>
      <div class="alert alert-info">
      <h2><span class="label label-info">Status</span> 待機中</h2>
      <p><span class="glyphicon glyphicon-exclamation-sign"></span> 計測中は他のデータを操作することはできなくなります。</p>
      <% end %>
    </div>
    </div>
  </div>
</div>


  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr><th>ID</th><th>Comment</th><th>Create Time</th><th>Action</th></tr>
    </thead>
    <tbody>
      <% @measurements.each do |m| %>
      <tr class="<%= 'danger' if m.id == @management.measurementid - 1 and @management.state == true %>"><td width="50" align="center"><%= m.id %></td>
        <td><%= m.comment %></td>
        <td width="250"><%= m.created_at %></td>
        <td width="230" align="center">
          <div class="btn-group">
            <% if m.id != @management.measurementid-1 and @management.state == true %>
            <%= link_to 'Show', "#", class: "btn btn-info disabled" %><%= link_to 'Edit', "#", class: "btn btn-success disabled" %><%= link_to 'Destroy', "#", :class => "btn btn-danger disabled" %>
            <% elsif m.id == @management.measurementid-1 and @management.state == true %>
            <%= link_to 'Show', measurement_path(m.id), class: "btn btn-info" %><%= link_to 'Edit', "#", class: "btn btn-success disabled" %><%= link_to 'Destroy', "#", :class => "btn btn-danger disabled" %>
            <% else %>
            <%= link_to 'Show', measurement_path(m.id), class: "btn btn-info" %><%= link_to 'Edit', edit_measurement_path(m.id), class: "btn btn-success" %><%= link_to 'Destroy', m, :data => {:confirm => "削除してもよろしいですか？"}, :class => "btn btn-danger", :method => :delete  %>
            <% end %>
          </div>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/measurements/new.html.erb
<h1>新しい計測を開始します</h1>
<h2>何かコメントがあれば入力してください(任意)</h2>

<%= simple_form_for(@measurement) do |f| %>
  <%= f.input :comment %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
  </div>
<% end %>

app/views/measurements/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="span12 pull-center">
      <div class="alert alert-info">
	<h1> <span class="label label-info">Measurement ID</span> <%= @measurement.id %> </h1>
	<h3> <span class="label label-info">Comment</span> <%= @measurement.comment %></h3>
      </div>
    </div>
  </div>
</div>

<div align="right">
<%= link_to  'Export CSV', export_csv_path, method: "GET", class: "btn btn-primary" %>
</div>

<div align="center">
<%= link_to  'Auto Reload Graph', auto_reload_path, method: "GET", class: "btn btn-info" %>
</div>

<ul class="nav nav-tabs">
  <li class="active"><a href="#Graph" data-toggle="tab">Graph</a></li>
  <li><a href="#Data" data-toggle="tab">Data</a></li>
</ul>


<div class="tab-content">
  <div class="tab-pane active" id="Graph">
    <%= image_tag "/images/graph-#{@measurement.id}.png" %>
  </div>

  <div class="tab-pane" id="Data">
    <% if @measurement.records.any? %>
    <table class="table table-striped table-bordered table-hover">
      <thead>
     	  <tr><th>ID</th><th>Depth</th><th>x</th><th>y</th></tr>
      </thead>
      <tbody>
	      <% @measurement.records.each do |r| %>
	      <tr>
        <td><%= r.id %></td>
	      <td><%= r.depth %></td>
	      <td><%= r.x %></td>
	      <td><%= r.y %></td>
	      </tr>
	      <% end %>
      </tbody>
    </table>
    <% else %>
      <h4>No data yet.</h4>
    <% end %>
  </div>
</div>